### ISSUE TITLE
Location of saved picture

### ISSUE THREAD

**Issue by GamingInsane** [Tanmay-Tiwaricyber/WcamPhish#4]
it says target opened the link. i opened the link myself. now i wanna see where the photo is saved. please help

**Comment by Tanmay-Tiwaricyber** [comment]
Which platform you use Kali Linux or termux

**Comment by GamingInsane** [comment]
Oh i solved my problem. actually no cam shots were  taken by my target so they were not saved.

**Comment by Tanmay-Tiwaricyber** [comment]
Please star my repo...

**Comment by Tanmay-Tiwaricyber** [comment]
Please star my repo...
