### ISSUE TITLE
Location of saved photo

### ISSUE THREAD

**Issue by PDVEVA** [Tanmay-Tiwaricyber/WcamPhish#5]
<img width="577" alt="Screenshot 2023-06-07 at 6 59 48 PM" src="https://github.com/Tanmay-Tiwaricyber/WcamPhish/assets/131574958/bef5392c-6780-4d7c-b8e6-73a719acaa6c">

Please help me with the location of the file received?

**Comment by Tanmay-Tiwaricyber** [comment]
Which application you use

**Comment by PDVEVA** [comment]
It's all good brother. I was able to locate it after going through my
system.

**Comment by Tanmay-Tiwaricyber** [comment]
bro star my repo

**Comment by PDVEVA** [comment]
Done
